/**
 * Tests for standalone static analysis -- works with any migration tool.
 *
 * Proves that `sqlever analyze` works as a general-purpose SQL linter
 * without any sqitch project, plan file, or config. Point it at any
 * .sql file from any migration framework and get actionable findings.
 *
 * Each test creates SQL files that mimic real-world migration patterns
 * from Flyway, Rails, Alembic, Django, golang-migrate, and raw SQL.
 * No sqitch.plan, no sqitch.conf, no sqlever.toml -- just SQL files.
 *
 * Covers:
 *   - Single file analysis with findings
 *   - Directory of unrelated SQL files
 *   - All four output formats (text, json, github-annotations, gitlab-codequality)
 *   - --strict mode (warnings become errors for exit code)
 *   - --force-rule suppression
 *   - Inline suppression (-- sqlever:disable)
 *   - Clean migration with zero findings
 *   - Exit codes (0 = clean, 2 = errors found)
 *   - CLI subprocess (proves end-to-end without project setup)
 *
 * Related: GitHub issue #164
 */

import { describe, test, expect, beforeAll, afterAll } from "bun:test";
import { loadModule } from "libpg-query";
import { runAnalyze } from "../../src/commands/analyze";
import { join } from "node:path";
import {
  mkdirSync,
  writeFileSync,
  rmSync,
  existsSync,
} from "node:fs";

// Ensure WASM module is loaded before tests
beforeAll(async () => {
  await loadModule();
});

// ---------------------------------------------------------------------------
// Temp directory -- no sqitch project structure, just loose SQL files
// ---------------------------------------------------------------------------

const TMP_DIR = join(import.meta.dir, "..", ".tmp-standalone-analysis");

beforeAll(() => {
  if (existsSync(TMP_DIR)) {
    rmSync(TMP_DIR, { recursive: true });
  }
  mkdirSync(TMP_DIR, { recursive: true });
  mkdirSync(join(TMP_DIR, "flyway"), { recursive: true });
  mkdirSync(join(TMP_DIR, "rails"), { recursive: true });
  mkdirSync(join(TMP_DIR, "alembic"), { recursive: true });
  mkdirSync(join(TMP_DIR, "django"), { recursive: true });
  mkdirSync(join(TMP_DIR, "golang-migrate"), { recursive: true });
  mkdirSync(join(TMP_DIR, "safe"), { recursive: true });
  mkdirSync(join(TMP_DIR, "mixed-dir"), { recursive: true });

  // -------------------------------------------------------------------------
  // Flyway-style migration with multiple problems
  // -------------------------------------------------------------------------
  writeFileSync(
    join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql"),
    `-- V42__add_status_to_orders.sql (Flyway naming convention)

ALTER TABLE orders ADD COLUMN status text NOT NULL;

CREATE INDEX idx_orders_status ON orders(status);

ALTER TABLE orders ALTER COLUMN total TYPE numeric(12,2);
`,
  );

  // -------------------------------------------------------------------------
  // Rails-style migration
  // -------------------------------------------------------------------------
  writeFileSync(
    join(TMP_DIR, "rails", "20240315_add_users.sql"),
    `-- Generated by Rails db:migrate

DROP TABLE IF EXISTS legacy_sessions;

UPDATE users SET role = 'member' WHERE role IS NULL;

ALTER TABLE users ADD CONSTRAINT chk_email CHECK (email ~ '@');
`,
  );

  // -------------------------------------------------------------------------
  // Alembic-style migration (Python/SQLAlchemy generated)
  // -------------------------------------------------------------------------
  writeFileSync(
    join(TMP_DIR, "alembic", "abc123_add_index.sql"),
    `-- Alembic revision abc123

CREATE INDEX ix_users_email ON users(email);
CREATE INDEX ix_users_created_at ON users(created_at);
`,
  );

  // -------------------------------------------------------------------------
  // Django-style migration
  // -------------------------------------------------------------------------
  writeFileSync(
    join(TMP_DIR, "django", "0042_add_field.sql"),
    `-- Django migration 0042

ALTER TABLE app_profile ADD COLUMN bio text NOT NULL;

DELETE FROM app_session;
`,
  );

  // -------------------------------------------------------------------------
  // golang-migrate style
  // -------------------------------------------------------------------------
  writeFileSync(
    join(TMP_DIR, "golang-migrate", "000003_add_audit.up.sql"),
    `-- golang-migrate: up migration

CREATE TABLE audit_log (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    action text NOT NULL,
    actor_id bigint,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_action ON audit_log(action);
`,
  );

  // -------------------------------------------------------------------------
  // Safe migration -- zero findings expected
  // -------------------------------------------------------------------------
  writeFileSync(
    join(TMP_DIR, "safe", "well_crafted.sql"),
    `-- A well-crafted migration: safe for large tables

SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS audit_log (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    action text NOT NULL,
    actor_id bigint,
    created_at timestamptz NOT NULL DEFAULT now()
);
`,
  );

  // -------------------------------------------------------------------------
  // File with inline suppressions (single-line form)
  // -------------------------------------------------------------------------
  writeFileSync(
    join(TMP_DIR, "suppressed.sql"),
    `CREATE INDEX idx_t_name ON t(name); -- sqlever:disable SA004,SA042,SA013
`,
  );

  // -------------------------------------------------------------------------
  // Mixed directory -- files from different frameworks side by side
  // -------------------------------------------------------------------------
  writeFileSync(
    join(TMP_DIR, "mixed-dir", "flyway_V1.sql"),
    `ALTER TABLE t ADD COLUMN x text NOT NULL;
`,
  );
  writeFileSync(
    join(TMP_DIR, "mixed-dir", "rails_001.sql"),
    `CREATE INDEX idx_t_x ON t(x);
`,
  );
  writeFileSync(
    join(TMP_DIR, "mixed-dir", "clean.sql"),
    `SET lock_timeout = '5s';
CREATE TABLE new_t (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY);
`,
  );
});

afterAll(() => {
  if (existsSync(TMP_DIR)) {
    rmSync(TMP_DIR, { recursive: true });
  }
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function silenceStdout(): () => void {
  const original = process.stdout.write.bind(process.stdout);
  process.stdout.write = (() => true) as typeof process.stdout.write;
  return () => {
    process.stdout.write = original;
  };
}

function captureStdout(): { getOutput: () => string; restore: () => void } {
  let output = "";
  const original = process.stdout.write.bind(process.stdout);
  process.stdout.write = ((chunk: unknown) => {
    output += typeof chunk === "string" ? chunk : String(chunk);
    return true;
  }) as typeof process.stdout.write;
  return {
    getOutput: () => output,
    restore: () => {
      process.stdout.write = original;
    },
  };
}

// ---------------------------------------------------------------------------
// Demo 1: Flyway migration -- standalone single file, no project setup
// ---------------------------------------------------------------------------

describe("standalone analysis -- Flyway migration", () => {
  test("detects SA001 (NOT NULL without DEFAULT) in Flyway file", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      const sa001 = result.findings.filter((f) => f.ruleId === "SA001");
      expect(sa001.length).toBe(1);
      expect(sa001[0]!.severity).toBe("error");
      expect(sa001[0]!.message).toContain("NOT NULL");
      expect(sa001[0]!.message).toContain("status");
      expect(sa001[0]!.suggestion).toBeDefined();
    } finally {
      restore();
    }
  });

  test("detects SA004 (CREATE INDEX without CONCURRENTLY)", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      const sa004 = result.findings.filter((f) => f.ruleId === "SA004");
      expect(sa004.length).toBe(1);
      expect(sa004[0]!.severity).toBe("warn");
      expect(sa004[0]!.message).toContain("idx_orders_status");
      expect(sa004[0]!.message).toContain("CONCURRENTLY");
    } finally {
      restore();
    }
  });

  test("detects SA003 (ALTER COLUMN TYPE rewrite)", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      const sa003 = result.findings.filter((f) => f.ruleId === "SA003");
      expect(sa003.length).toBe(1);
      expect(sa003[0]!.severity).toBe("error");
      expect(sa003[0]!.message).toContain("total");
    } finally {
      restore();
    }
  });

  test("detects SA013 (missing lock_timeout)", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      const sa013 = result.findings.filter((f) => f.ruleId === "SA013");
      expect(sa013.length).toBeGreaterThanOrEqual(3);
    } finally {
      restore();
    }
  });

  test("exit code 2 due to error-level findings", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      expect(result.exitCode).toBe(2);
      expect(result.filesAnalyzed).toBe(1);
    } finally {
      restore();
    }
  });
});

// ---------------------------------------------------------------------------
// Demo 2: Rails migration
// ---------------------------------------------------------------------------

describe("standalone analysis -- Rails migration", () => {
  test("detects SA007 (DROP TABLE data loss)", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "rails", "20240315_add_users.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      const sa007 = result.findings.filter((f) => f.ruleId === "SA007");
      expect(sa007.length).toBe(1);
      expect(sa007[0]!.severity).toBe("error");
      expect(sa007[0]!.message).toContain("legacy_sessions");
    } finally {
      restore();
    }
  });

  test("detects SA016 (CHECK constraint without NOT VALID)", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "rails", "20240315_add_users.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      const sa016 = result.findings.filter((f) => f.ruleId === "SA016");
      expect(sa016.length).toBe(1);
      expect(sa016[0]!.severity).toBe("error");
      expect(sa016[0]!.message).toContain("chk_email");
      expect(sa016[0]!.message).toContain("NOT VALID");
    } finally {
      restore();
    }
  });

  test("detects SA013 (missing lock_timeout) for DDL statements", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "rails", "20240315_add_users.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      const sa013 = result.findings.filter((f) => f.ruleId === "SA013");
      expect(sa013.length).toBeGreaterThanOrEqual(1);
    } finally {
      restore();
    }
  });
});

// ---------------------------------------------------------------------------
// Demo 3: Safe migration -- zero findings
// ---------------------------------------------------------------------------

describe("standalone analysis -- safe migration", () => {
  test("zero findings for a well-crafted migration", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "safe", "well_crafted.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      expect(result.findings.length).toBe(0);
      expect(result.exitCode).toBe(0);
      expect(result.filesAnalyzed).toBe(1);
    } finally {
      restore();
    }
  });

  test("text output says 'No issues found.'", async () => {
    const cap = captureStdout();
    try {
      await runAnalyze({
        targets: [join(TMP_DIR, "safe", "well_crafted.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      expect(cap.getOutput()).toContain("No issues found.");
    } finally {
      cap.restore();
    }
  });
});

// ---------------------------------------------------------------------------
// Demo 4: Alembic migration -- multiple indexes without CONCURRENTLY
// ---------------------------------------------------------------------------

describe("standalone analysis -- Alembic migration", () => {
  test("detects SA004 for each index", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "alembic", "abc123_add_index.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      const sa004 = result.findings.filter((f) => f.ruleId === "SA004");
      expect(sa004.length).toBe(2);
      expect(sa004[0]!.message).toContain("ix_users_email");
      expect(sa004[1]!.message).toContain("ix_users_created_at");
    } finally {
      restore();
    }
  });
});

// ---------------------------------------------------------------------------
// Demo 5: Django migration -- ADD COLUMN NOT NULL + DELETE without WHERE
// ---------------------------------------------------------------------------

describe("standalone analysis -- Django migration", () => {
  test("detects SA001 (NOT NULL without DEFAULT)", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "django", "0042_add_field.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      const sa001 = result.findings.filter((f) => f.ruleId === "SA001");
      expect(sa001.length).toBe(1);
      expect(sa001[0]!.message).toContain("bio");
    } finally {
      restore();
    }
  });

  test("detects SA010 (DELETE without WHERE)", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "django", "0042_add_field.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      const sa010 = result.findings.filter((f) => f.ruleId === "SA010");
      expect(sa010.length).toBe(1);
      expect(sa010[0]!.severity).toBe("warn");
    } finally {
      restore();
    }
  });
});

// ---------------------------------------------------------------------------
// Demo 6: golang-migrate -- CREATE TABLE is clean but index is not
// ---------------------------------------------------------------------------

describe("standalone analysis -- golang-migrate", () => {
  test("CREATE TABLE passes clean, CREATE INDEX triggers SA004", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "golang-migrate", "000003_add_audit.up.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      // No SA001 -- CREATE TABLE with NOT NULL + DEFAULT is fine
      const sa001 = result.findings.filter((f) => f.ruleId === "SA001");
      expect(sa001.length).toBe(0);
      // SA004 for the non-concurrent index
      const sa004 = result.findings.filter((f) => f.ruleId === "SA004");
      expect(sa004.length).toBe(1);
      expect(sa004[0]!.message).toContain("idx_audit_action");
    } finally {
      restore();
    }
  });
});

// ---------------------------------------------------------------------------
// Directory scanning -- analyze a whole directory of unrelated SQL files
// ---------------------------------------------------------------------------

describe("standalone analysis -- directory of mixed files", () => {
  test("analyzes all .sql files in a directory without project setup", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "mixed-dir")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      expect(result.filesAnalyzed).toBe(3);
      // SA001 from flyway_V1.sql
      const sa001 = result.findings.filter((f) => f.ruleId === "SA001");
      expect(sa001.length).toBe(1);
      // SA004 from rails_001.sql
      const sa004 = result.findings.filter((f) => f.ruleId === "SA004");
      expect(sa004.length).toBe(1);
    } finally {
      restore();
    }
  });

  test("exit code 2 when any file has error-level findings", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "mixed-dir")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      expect(result.exitCode).toBe(2);
    } finally {
      restore();
    }
  });
});

// ---------------------------------------------------------------------------
// Output formats -- all four formats work without project setup
// ---------------------------------------------------------------------------

describe("standalone analysis -- output formats", () => {
  const flywayFile = () =>
    join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql");

  test("text format includes severity, rule ID, and suggestion", async () => {
    const cap = captureStdout();
    try {
      await runAnalyze({
        targets: [flywayFile()],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      const output = cap.getOutput();
      expect(output).toContain("error");
      expect(output).toContain("SA001");
      expect(output).toContain("suggestion:");
      expect(output).toMatch(/\d+ error/);
    } finally {
      cap.restore();
    }
  });

  test("json format produces valid structured report", async () => {
    const cap = captureStdout();
    try {
      await runAnalyze({
        targets: [flywayFile()],
        format: "json",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      const parsed = JSON.parse(cap.getOutput());
      expect(parsed.version).toBe(1);
      expect(parsed.metadata.files_analyzed).toBe(1);
      expect(parsed.metadata.rules_checked).toBeGreaterThan(20);
      expect(parsed.metadata.duration_ms).toBeGreaterThanOrEqual(0);
      expect(Array.isArray(parsed.findings)).toBe(true);
      expect(parsed.findings.length).toBeGreaterThan(0);
      expect(parsed.summary.errors).toBeGreaterThan(0);
      // Verify each finding has required fields
      for (const f of parsed.findings) {
        expect(f.ruleId).toMatch(/^SA\d{3}/);
        expect(["error", "warn", "info"]).toContain(f.severity);
        expect(typeof f.message).toBe("string");
        expect(f.location.file).toBeDefined();
        expect(typeof f.location.line).toBe("number");
        expect(typeof f.location.column).toBe("number");
      }
    } finally {
      cap.restore();
    }
  });

  test("github-annotations format produces :: prefixed lines", async () => {
    const cap = captureStdout();
    try {
      await runAnalyze({
        targets: [flywayFile()],
        format: "github-annotations",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      const output = cap.getOutput();
      const lines = output.trim().split("\n");
      expect(lines.length).toBeGreaterThan(0);
      for (const line of lines) {
        expect(line).toMatch(/^::(error|warning|notice) file=/);
      }
      // Should contain both error and warning level annotations
      expect(output).toContain("::error");
      expect(output).toContain("::warning");
    } finally {
      cap.restore();
    }
  });

  test("gitlab-codequality format produces valid JSON array", async () => {
    const cap = captureStdout();
    try {
      await runAnalyze({
        targets: [flywayFile()],
        format: "gitlab-codequality",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      const parsed = JSON.parse(cap.getOutput());
      expect(Array.isArray(parsed)).toBe(true);
      expect(parsed.length).toBeGreaterThan(0);
      for (const entry of parsed) {
        expect(entry.check_name).toMatch(/^SA\d{3}/);
        expect(["critical", "major", "minor"]).toContain(entry.severity);
        expect(entry.fingerprint).toMatch(/^[a-f0-9]{40}$/);
        expect(entry.location.path).toBeDefined();
        expect(typeof entry.location.lines.begin).toBe("number");
        expect(typeof entry.description).toBe("string");
      }
    } finally {
      cap.restore();
    }
  });
});

// ---------------------------------------------------------------------------
// --strict mode -- warnings become errors for exit code
// ---------------------------------------------------------------------------

describe("standalone analysis -- --strict mode", () => {
  test("warnings produce exit code 2 with --strict", async () => {
    const restore = silenceStdout();
    try {
      // Alembic file has SA004 (warn) and SA013 (warn) -- --strict promotes warn to error
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "alembic", "abc123_add_index.sql")],
        format: "text",
        strict: true,
        all: false,
        changed: false,
        forceRules: [],
      });
      // warn findings should be promoted to error; info stays info
      const warnFindings = result.findings.filter(
        (f) => f.severity === "warn",
      );
      expect(warnFindings.length).toBe(0);
      // At least some error findings (promoted from warn)
      const errorFindings = result.findings.filter(
        (f) => f.severity === "error",
      );
      expect(errorFindings.length).toBeGreaterThan(0);
      expect(result.exitCode).toBe(2);
    } finally {
      restore();
    }
  });

  test("clean file still exits 0 with --strict", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "safe", "well_crafted.sql")],
        format: "text",
        strict: true,
        all: false,
        changed: false,
        forceRules: [],
      });
      expect(result.exitCode).toBe(0);
    } finally {
      restore();
    }
  });
});

// ---------------------------------------------------------------------------
// --force-rule -- suppress specific rules
// ---------------------------------------------------------------------------

describe("standalone analysis -- --force-rule", () => {
  test("suppresses SA004 while other rules still fire", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: ["SA004"],
      });
      const sa004 = result.findings.filter((f) => f.ruleId === "SA004");
      expect(sa004.length).toBe(0);
      // Other rules should still fire
      const sa001 = result.findings.filter((f) => f.ruleId === "SA001");
      expect(sa001.length).toBe(1);
    } finally {
      restore();
    }
  });

  test("suppresses multiple rules", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: ["SA001", "SA003", "SA004", "SA013"],
      });
      const suppressed = result.findings.filter(
        (f) =>
          f.ruleId === "SA001" ||
          f.ruleId === "SA003" ||
          f.ruleId === "SA004" ||
          f.ruleId === "SA013",
      );
      expect(suppressed.length).toBe(0);
    } finally {
      restore();
    }
  });
});

// ---------------------------------------------------------------------------
// Inline suppression -- works without any project setup
// ---------------------------------------------------------------------------

describe("standalone analysis -- inline suppression", () => {
  test("-- sqlever:disable on same line suppresses matching findings", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "suppressed.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      // All three rules (SA004, SA042, SA013) suppressed via single-line comment
      const sa004 = result.findings.filter((f) => f.ruleId === "SA004");
      const sa042 = result.findings.filter((f) => f.ruleId === "SA042");
      const sa013 = result.findings.filter((f) => f.ruleId === "SA013");
      expect(sa004.length).toBe(0);
      expect(sa042.length).toBe(0);
      expect(sa013.length).toBe(0);
      // No real findings remain (only suppression-related warnings are acceptable)
      const realFindings = result.findings.filter(
        (f) => f.ruleId !== "suppression",
      );
      expect(realFindings.length).toBe(0);
    } finally {
      restore();
    }
  });
});

// ---------------------------------------------------------------------------
// No sqitch.plan fallback -- explicit targets bypass plan discovery
// ---------------------------------------------------------------------------

describe("standalone analysis -- no sqitch.plan needed", () => {
  test("explicit file target works without any plan file", async () => {
    const restore = silenceStdout();
    try {
      // TMP_DIR has no sqitch.plan -- this is the key point
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      expect(result.filesAnalyzed).toBe(1);
      expect(result.findings.length).toBeGreaterThan(0);
    } finally {
      restore();
    }
  });

  test("directory target works without any plan file", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "alembic")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      expect(result.filesAnalyzed).toBe(1);
      expect(result.findings.length).toBeGreaterThan(0);
    } finally {
      restore();
    }
  });

  test("multiple targets from different frameworks in one call", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [
          join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql"),
          join(TMP_DIR, "rails", "20240315_add_users.sql"),
          join(TMP_DIR, "django", "0042_add_field.sql"),
        ],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      expect(result.filesAnalyzed).toBe(3);
      // Should find issues from all three files
      const uniqueRuleIds = new Set(result.findings.map((f) => f.ruleId));
      expect(uniqueRuleIds.has("SA001")).toBe(true); // Flyway + Django
      expect(uniqueRuleIds.has("SA007")).toBe(true); // Rails DROP TABLE
    } finally {
      restore();
    }
  });
});

// ---------------------------------------------------------------------------
// Exit codes
// ---------------------------------------------------------------------------

describe("standalone analysis -- exit codes", () => {
  test("exit code 0 for clean file", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "safe", "well_crafted.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      expect(result.exitCode).toBe(0);
    } finally {
      restore();
    }
  });

  test("exit code 2 for file with errors", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      expect(result.exitCode).toBe(2);
    } finally {
      restore();
    }
  });

  test("exit code 0 for warnings only (without --strict)", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "alembic", "abc123_add_index.sql")],
        format: "text",
        strict: false,
        all: false,
        changed: false,
        forceRules: [],
      });
      // Only SA004 (warn) and SA013 (warn) -- no errors
      const hasErrorRule = result.findings.some(
        (f) => f.severity === "error",
      );
      expect(hasErrorRule).toBe(false);
      expect(result.exitCode).toBe(0);
    } finally {
      restore();
    }
  });

  test("exit code 2 for warnings with --strict", async () => {
    const restore = silenceStdout();
    try {
      const result = await runAnalyze({
        targets: [join(TMP_DIR, "alembic", "abc123_add_index.sql")],
        format: "text",
        strict: true,
        all: false,
        changed: false,
        forceRules: [],
      });
      expect(result.exitCode).toBe(2);
    } finally {
      restore();
    }
  });
});

// ---------------------------------------------------------------------------
// CLI subprocess -- end-to-end without project setup
// ---------------------------------------------------------------------------

describe("standalone analysis -- CLI subprocess", () => {
  const CLI_PATH = join(import.meta.dir, "..", "..", "src", "cli.ts");

  test("sqlever analyze <file> works on standalone SQL", async () => {
    const file = join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql");
    const proc = Bun.spawn(["bun", "run", CLI_PATH, "analyze", file], {
      stdout: "pipe",
      stderr: "pipe",
    });
    const exitCode = await proc.exited;
    expect(exitCode).toBe(2);
  });

  test("sqlever analyze <dir> scans directory of standalone SQL", async () => {
    const proc = Bun.spawn(
      ["bun", "run", CLI_PATH, "analyze", join(TMP_DIR, "mixed-dir")],
      {
        stdout: "pipe",
        stderr: "pipe",
      },
    );
    const exitCode = await proc.exited;
    expect(exitCode).toBe(2);
  });

  test("sqlever analyze --format json <file> produces valid JSON", async () => {
    const file = join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql");
    const proc = Bun.spawn(
      ["bun", "run", CLI_PATH, "analyze", "--format", "json", file],
      {
        stdout: "pipe",
        stderr: "pipe",
      },
    );
    const stdout = await new Response(proc.stdout).text();
    await proc.exited;
    const parsed = JSON.parse(stdout);
    expect(parsed.version).toBe(1);
    expect(parsed.findings.length).toBeGreaterThan(0);
  });

  test("sqlever analyze --format github-annotations <file> produces annotations", async () => {
    const file = join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql");
    const proc = Bun.spawn(
      [
        "bun",
        "run",
        CLI_PATH,
        "analyze",
        "--format",
        "github-annotations",
        file,
      ],
      {
        stdout: "pipe",
        stderr: "pipe",
      },
    );
    const stdout = await new Response(proc.stdout).text();
    await proc.exited;
    expect(stdout).toContain("::error");
    expect(stdout).toContain("::warning");
  });

  test("sqlever analyze --format gitlab-codequality <file> produces codequality JSON", async () => {
    const file = join(TMP_DIR, "flyway", "V42__add_status_to_orders.sql");
    const proc = Bun.spawn(
      [
        "bun",
        "run",
        CLI_PATH,
        "analyze",
        "--format",
        "gitlab-codequality",
        file,
      ],
      {
        stdout: "pipe",
        stderr: "pipe",
      },
    );
    const stdout = await new Response(proc.stdout).text();
    await proc.exited;
    const parsed = JSON.parse(stdout);
    expect(Array.isArray(parsed)).toBe(true);
    expect(parsed.length).toBeGreaterThan(0);
    expect(parsed[0].fingerprint).toMatch(/^[a-f0-9]{40}$/);
  });

  test("sqlever analyze --strict <file> treats warnings as errors", async () => {
    const file = join(TMP_DIR, "alembic", "abc123_add_index.sql");
    const proc = Bun.spawn(
      ["bun", "run", CLI_PATH, "analyze", "--strict", file],
      {
        stdout: "pipe",
        stderr: "pipe",
      },
    );
    const exitCode = await proc.exited;
    expect(exitCode).toBe(2);
  });

  test("sqlever analyze <safe-file> exits 0 for clean migration", async () => {
    const file = join(TMP_DIR, "safe", "well_crafted.sql");
    const proc = Bun.spawn(["bun", "run", CLI_PATH, "analyze", file], {
      stdout: "pipe",
      stderr: "pipe",
    });
    const exitCode = await proc.exited;
    expect(exitCode).toBe(0);
  });
});
